apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-{{ .Chart.Name }}
data:
  application.properties: |-
    spring.datasource.url={{ .Values.db.url }}
    spring.datasource.username=${DB_USER}
    spring.datasource.password=${DB_PASSWORD}
    server.port={{ .Values.service.port }}
    management.endpoint.metrics.enabled=true
    management.endpoint.configprops.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=always